<a href="https://colab.research.google.com/github/harsh43580/Pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU.")

GPU is available
Using GPU: Tesla T4


# Creating Tensor

In [5]:
# using empty
a = torch.empty(2,3)

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using one
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.9754, 0.7720, 0.9084],
        [0.5225, 0.2354, 0.8835]])

In [10]:
# use of seed
torch.manual_seed(1729)
torch.rand(2,3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# using arange
print("using arange ->", torch.arange(0, 10, 2))

# using linspace
print("using linspace ->", torch.linspace(0, 10, 5))

# using eye (FIXED: it's `eye`, not `eyes`)
print("using eye ->", torch.eye(5))

# using full (FIXED: missing closing parenthesis)
print("using full ->", torch.full((2, 3), 7))  # Also needs a fill value!

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[7, 7, 7],
        [7, 7, 7]])


# Tensor Shapes

In [17]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[    139338250173840,     139338250173840,                   0],
        [                  0,                   0, 7310593858020254331]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor Data Types


In [22]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operation

1. Scalar Operation

In [28]:
x = torch.rand(2,2)
x

tensor([[0.2332, 0.4047],
        [0.2162, 0.9927]])

In [29]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 2
# division
x / 2
# int division
x // 2
# power
x ** 2
# mod
((x * 100)//3)%2

tensor([[1., 1.],
        [1., 1.]])

2. Element wise Operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4128, 0.5938, 0.6128],
        [0.1519, 0.0453, 0.5035]])
tensor([[0.9978, 0.3884, 0.6929],
        [0.1703, 0.1384, 0.4759]])


In [31]:
# add
a + b
# sub
a - b
# multiplication
a * b


tensor([[0.4119, 0.2306, 0.4246],
        [0.0259, 0.0063, 0.2396]])